# Generated by Django 3.2.11 on 2022-05-19 15:33

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_alter_offer_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-last_bump']},
        ),
        migrations.AlterModelManagers(
            name='offer',
            managers=[
                ('active_offer_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='offer',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
